apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mywebappdeploy
  labels:
    name:  mywebapp
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mywebapp
    spec:
      containers:
      - image:  koteswarararaosairi/project
        name:  mywebapp
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  5000
          name:  my-name
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always
 ---
apiVersion: v1
kind: Service
metadata:
  name:  mywebappservice
spec:
  selector:
    app:  Selector Label
  type:   NodePort
  ports:
  - name: mywebapp
    port:  80
    targetPort:  8080
    nodeport: 30736
      
