---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: koti-deployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: koti-koti
 template:
  metadata:
   name: koti-kotipod
   labels:
     app: koti-koti	 
  spec: 
    containers:
    - name: koti-koti
      image: koteswarararaosairi/kk:v6
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: koti-service
spec:
  type: NodePort
  selector:
   app: koti-koti
  ports:
   - port: 80
     targetPort: 8080
...
